<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from "vue";
import { EditorState, StateEffect, StateField } from "@codemirror/state";
import { Decoration, EditorView, keymap } from "@codemirror/view";
import { defaultKeymap } from "@codemirror/commands";
import { markdown } from "@codemirror/lang-markdown";
const props = withDefaults(defineProps<{ modelValue: string; readonly?: boolean }>(), { readonly: false });
const emit = defineEmits<{ "update:modelValue": [value: string, kind: "typing" | "delete"]; "selection-change": [from: number, to: number]; scroll: [ratio: number, line: number]; "context-menu": [x: number, y: number]; undo: []; redo: []; save: [] }>();
const root = ref<HTMLElement>(); let view: EditorView | undefined; let applying = false; let highlightTimer: number | undefined;
function debugScroll(phase: string, detail: Record<string, number | undefined>) { if (import.meta.env.DEV && window.localStorage.getItem("mdtool:debug-scroll") === "1") console.log("[mdTool][scroll]", phase, detail); }
const setJumpHighlight = StateEffect.define<{ from: number; to: number }>(); const clearJumpHighlight = StateEffect.define<null>();
const jumpHighlight = StateField.define({ create: () => Decoration.none, update(value, transaction) { for (const effect of transaction.effects) { if (effect.is(clearJumpHighlight)) return Decoration.none; if (effect.is(setJumpHighlight)) return Decoration.set([Decoration.mark({ class: "cm-jump-highlight" }).range(effect.value.from, effect.value.to)]); } return value.map(transaction.changes); }, provide: field => EditorView.decorations.from(field) });
const cursorTheme = EditorView.theme({ ".cm-cursor, .cm-focused .cm-cursor": { borderLeft: "2px solid var(--cursor) !important" }, ".cm-dropCursor": { borderLeft: "2px solid var(--cursor) !important" }, ".cm-content": { caretColor: "var(--cursor) !important" } });
type ViewportAnchor = { position: number; offset: number };
function captureViewportAnchor(): ViewportAnchor | undefined { if (!view) return undefined; const scrollerTop = view.scrollDOM.getBoundingClientRect().top; const topHeight = scrollerTop - view.documentTop; const position = view.lineBlockAtHeight(topHeight).from; const coords = view.coordsAtPos(position); return coords ? { position, offset: coords.top - scrollerTop } : undefined; }
function mapPosition(previous: string, next: string, position: number) { let prefix = 0; const shared = Math.min(previous.length, next.length); while (prefix < shared && previous.charCodeAt(prefix) === next.charCodeAt(prefix)) prefix += 1; let suffix = 0; while (suffix < previous.length - prefix && suffix < next.length - prefix && previous.charCodeAt(previous.length - 1 - suffix) === next.charCodeAt(next.length - 1 - suffix)) suffix += 1; const previousEnd = previous.length - suffix; const nextEnd = next.length - suffix; if (position <= prefix) return position; if (position >= previousEnd) return position + nextEnd - previousEnd; return Math.min(nextEnd, prefix + position - prefix); }
function restoreViewportAnchor(anchor: ViewportAnchor, previous: string, next: string) { if (!view) return; const position = Math.max(0, Math.min(mapPosition(previous, next, anchor.position), view.state.doc.length)); const coords = view.coordsAtPos(position); if (!coords) return; const before = view.scrollDOM.scrollTop; const delta = coords.top - view.scrollDOM.getBoundingClientRect().top - anchor.offset; view.scrollDOM.scrollTop += delta; debugScroll("anchor-restored", { position, before, delta, after: view.scrollDOM.scrollTop }); }
function scrollState() { if (!view) return [0, 1] as const; const max = Math.max(1, view.scrollDOM.scrollHeight - view.scrollDOM.clientHeight); const viewportMiddle = view.scrollDOM.getBoundingClientRect().top - view.documentTop + view.scrollDOM.clientHeight / 2; const middleLine = view.lineBlockAtHeight(viewportMiddle).from; return [view.scrollDOM.scrollTop / max, view.state.doc.lineAt(middleLine).number] as const; }
function scrollToPosition(position: number) { if (!view) return; const pos = Math.max(0, Math.min(position, view.state.doc.length)); view.dispatch({ selection: { anchor: pos }, effects: EditorView.scrollIntoView(pos, { y: "center" }) }); view.focus(); }
function highlightRange(from: number, to: number) { if (!view) return; const start = Math.max(0, Math.min(from, view.state.doc.length)); const end = Math.max(start + 1, Math.min(to, view.state.doc.length)); window.clearTimeout(highlightTimer); view.dispatch({ selection: { anchor: start }, effects: [setJumpHighlight.of({ from: start, to: end }), EditorView.scrollIntoView(start, { y: "center" })] }); highlightTimer = window.setTimeout(() => view?.dispatch({ effects: clearJumpHighlight.of(null) }), 1500); view.focus(); }
function setScrollRatio(next: number) { if (!view) return; const max = Math.max(0, view.scrollDOM.scrollHeight - view.scrollDOM.clientHeight); view.scrollDOM.scrollTop = Math.max(0, Math.min(1, next)) * max; }
function scrollToLine(line: number) { if (!view) return; const target = view.state.doc.line(Math.max(1, Math.min(line, view.state.doc.lines))).from; view.dispatch({ effects: EditorView.scrollIntoView(target, { y: "center" }) }); }
async function copySelection() { if (!view) return; const range = view.state.selection.main; await navigator.clipboard.writeText(view.state.sliceDoc(range.from, range.to)); }
async function cutSelection() { if (!view || props.readonly) return; const range = view.state.selection.main; await navigator.clipboard.writeText(view.state.sliceDoc(range.from, range.to)); view.dispatch({ changes: { from: range.from, to: range.to }, selection: { anchor: range.from } }); view.focus(); }
async function pasteClipboard() { if (!view || props.readonly) return; const text = await navigator.clipboard.readText(); const range = view.state.selection.main; view.dispatch({ changes: { from: range.from, to: range.to, insert: text }, selection: { anchor: range.from + text.length } }); view.focus(); }
defineExpose({ scrollToPosition, highlightRange, setScrollRatio, scrollToLine, copySelection, cutSelection, pasteClipboard });
onMounted(() => { view = new EditorView({ state: EditorState.create({ doc: props.modelValue, extensions: [markdown(), jumpHighlight, cursorTheme, EditorState.readOnly.of(props.readonly), EditorView.editable.of(!props.readonly), keymap.of([{ key: "Mod-s", run: () => { emit("save"); return true; } }, { key: "Mod-z", run: () => { emit("undo"); return true; } }, { key: "Mod-Shift-z", run: () => { emit("redo"); return true; } }, { key: "Mod-y", run: () => { emit("redo"); return true; } }, ...defaultKeymap]), EditorView.lineWrapping, EditorView.updateListener.of(update => { if (update.docChanged && !applying && !props.readonly) { const kind = update.transactions.some(transaction => transaction.isUserEvent("delete")) ? "delete" : "typing"; emit("update:modelValue", update.state.doc.toString(), kind); } if (update.selectionSet && !applying && !props.readonly) { const range = update.state.selection.main; emit("selection-change", range.from, range.to); } })] }), parent: root.value }); view.scrollDOM.addEventListener("scroll", () => emit("scroll", ...scrollState())); view.dom.addEventListener("contextmenu", event => { event.preventDefault(); emit("context-menu", event.clientX, event.clientY); }); });
watch(() => props.modelValue, value => { if (!view || value === view.state.doc.toString()) return; const previous = view.state.doc.toString(); const anchor = captureViewportAnchor(); debugScroll("external-update-before", { scrollTop: view.scrollDOM.scrollTop, scrollHeight: view.scrollDOM.scrollHeight, anchorPosition: anchor?.position, anchorOffset: anchor?.offset }); applying = true; view.dispatch({ changes: { from: 0, to: view.state.doc.length, insert: value } }); applying = false; debugScroll("external-update-dispatched", { scrollTop: view.scrollDOM.scrollTop, scrollHeight: view.scrollDOM.scrollHeight }); if (anchor) requestAnimationFrame(() => { restoreViewportAnchor(anchor, previous, value); requestAnimationFrame(() => debugScroll("two-frames-later", { scrollTop: view?.scrollDOM.scrollTop, scrollHeight: view?.scrollDOM.scrollHeight })); }); }); onBeforeUnmount(() => { window.clearTimeout(highlightTimer); view?.destroy(); });
</script>
<template><div ref="root" class="editor" :class="{ readonly }" lang="en" spellcheck="false" aria-label="Markdown 源码编辑器" /></template>
<style scoped>.editor { height: 100%; min-height: 0; }.editor :deep(.cm-editor) { height: 100%; font: 15px/1.75 "Cascadia Code", "Sarasa Mono SC", monospace; background: var(--editor); color: var(--text); caret-color: var(--cursor) !important; }.readonly :deep(.cm-editor) { background: var(--panel); }.editor :deep(.cm-scroller) { padding: 1.5rem; }.editor :deep(.cm-gutters) { background: var(--editor); color: var(--muted); border: 0; }.readonly :deep(.cm-gutters) { background: var(--panel); }.editor :deep(.cm-cursor),.editor :deep(.cm-focused .cm-cursor),.editor :deep(.cm-dropCursor) { border-left: 2px solid var(--cursor)!important; }.editor :deep(.cm-content) { caret-color: var(--cursor) !important; }.editor :deep(.cm-jump-highlight) { background: var(--jump-highlight); outline: 1px solid var(--jump-outline); border-radius: 2px; animation: jump-flash 1.5s ease-out; }@keyframes jump-flash { 0%,45% { background: var(--jump-highlight-strong); } 100% { background: var(--jump-highlight); } }</style>
