<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from "vue";
import { EditorState, StateEffect, StateField } from "@codemirror/state";
import { Decoration, EditorView, keymap } from "@codemirror/view";
import { defaultKeymap } from "@codemirror/commands";
import { markdown } from "@codemirror/lang-markdown";
const props = withDefaults(defineProps<{ modelValue: string; readonly?: boolean }>(), { readonly: false });
const emit = defineEmits<{ "update:modelValue": [value: string, kind: "typing" | "delete"]; "paste-document": [value: string]; "selection-change": [from: number, to: number]; scroll: [ratio: number]; undo: []; redo: [] }>();
const root = ref<HTMLElement>(); let view: EditorView | undefined; let applying = false; let highlightTimer: number | undefined;
const setJumpHighlight = StateEffect.define<{ from: number; to: number }>(); const clearJumpHighlight = StateEffect.define<null>();
const jumpHighlight = StateField.define({ create: () => Decoration.none, update(value, transaction) { for (const effect of transaction.effects) { if (effect.is(clearJumpHighlight)) return Decoration.none; if (effect.is(setJumpHighlight)) return Decoration.set([Decoration.mark({ class: "cm-jump-highlight" }).range(effect.value.from, effect.value.to)]); } return value.map(transaction.changes); }, provide: field => EditorView.decorations.from(field) });
const cursorTheme = EditorView.theme({ ".cm-cursor": { borderLeft: "2px solid var(--cursor) !important" }, ".cm-dropCursor": { borderLeft: "2px solid var(--cursor) !important" } });
function ratio() { if (!view) return 0; const max = Math.max(1, view.scrollDOM.scrollHeight - view.scrollDOM.clientHeight); return view.scrollDOM.scrollTop / max; }
function scrollToPosition(position: number) { if (!view) return; const pos = Math.max(0, Math.min(position, view.state.doc.length)); view.dispatch({ selection: { anchor: pos }, effects: EditorView.scrollIntoView(pos, { y: "center" }) }); view.focus(); }
function highlightRange(from: number, to: number) { if (!view) return; const start = Math.max(0, Math.min(from, view.state.doc.length)); const end = Math.max(start + 1, Math.min(to, view.state.doc.length)); window.clearTimeout(highlightTimer); view.dispatch({ selection: { anchor: start }, effects: [setJumpHighlight.of({ from: start, to: end }), EditorView.scrollIntoView(start, { y: "center" })] }); highlightTimer = window.setTimeout(() => view?.dispatch({ effects: clearJumpHighlight.of(null) }), 1500); view.focus(); }
function setScrollRatio(next: number) { if (!view) return; const max = Math.max(0, view.scrollDOM.scrollHeight - view.scrollDOM.clientHeight); view.scrollDOM.scrollTop = Math.max(0, Math.min(1, next)) * max; }
defineExpose({ scrollToPosition, highlightRange, setScrollRatio });
onMounted(() => { view = new EditorView({ state: EditorState.create({ doc: props.modelValue, extensions: [markdown(), jumpHighlight, cursorTheme, EditorState.readOnly.of(props.readonly), EditorView.editable.of(!props.readonly), keymap.of([{ key: "Mod-z", run: () => { emit("undo"); return true; } }, { key: "Mod-Shift-z", run: () => { emit("redo"); return true; } }, { key: "Mod-y", run: () => { emit("redo"); return true; } }, ...defaultKeymap]), EditorView.lineWrapping, EditorView.domEventHandlers({ paste(event) { if (props.readonly) return true; const pasted = event.clipboardData?.getData("text/plain"); if (pasted === undefined) return false; event.preventDefault(); emit("paste-document", pasted); return true; } }), EditorView.updateListener.of(update => { if (update.docChanged && !applying && !props.readonly) { const kind = update.transactions.some(transaction => transaction.isUserEvent("delete")) ? "delete" : "typing"; emit("update:modelValue", update.state.doc.toString(), kind); } if (update.selectionSet && !applying && !props.readonly) { const range = update.state.selection.main; emit("selection-change", range.from, range.to); } })] }), parent: root.value }); view.scrollDOM.addEventListener("scroll", () => emit("scroll", ratio())); });
watch(() => props.modelValue, value => { if (!view || value === view.state.doc.toString()) return; applying = true; view.dispatch({ changes: { from: 0, to: view.state.doc.length, insert: value } }); applying = false; }); onBeforeUnmount(() => { window.clearTimeout(highlightTimer); view?.destroy(); });
</script>
<template><div ref="root" class="editor" :class="{ readonly }" aria-label="Markdown 源码编辑器" /></template>
<style scoped>.editor { height: 100%; min-height: 0; }.editor :deep(.cm-editor) { height: 100%; font: 15px/1.75 "Cascadia Code", "Sarasa Mono SC", monospace; background: var(--editor); color: var(--text); caret-color: var(--cursor); }.readonly :deep(.cm-editor) { background: var(--panel); }.editor :deep(.cm-scroller) { padding: 1.5rem; }.editor :deep(.cm-gutters) { background: var(--editor); color: var(--muted); border: 0; }.readonly :deep(.cm-gutters) { background: var(--panel); }.editor :deep(.cm-cursor),.editor :deep(.cm-dropCursor) { border-left: 2px solid var(--cursor)!important; }.editor :deep(.cm-jump-highlight) { background: var(--jump-highlight); outline: 1px solid var(--jump-outline); border-radius: 2px; animation: jump-flash 1.5s ease-out; }@keyframes jump-flash { 0%,45% { background: var(--jump-highlight-strong); } 100% { background: var(--jump-highlight); } }</style>
