import type { SectionNode, TextEdit } from "../types";
import { applyEdits } from "./textEdits";

const heading = /^( {0,3})(#{1,6})[ \t]+(.+?)[ \t]*#*[ \t]*$/gm;
export function parseNumber(title: string): { parts: number[] | null; text: string } { const found = /^(\d+(?:\.\d+)*)[.)]?\s+(.+)$/.exec(title.trim()); return found ? { parts: found[1].split(".").map(Number), text: found[2] } : { parts: null, text: title.trim() }; }
export function buildSectionTree(text: string): SectionNode[] {
  const flat: SectionNode[] = []; let match: RegExpExecArray | null;
  while ((match = heading.exec(text))) { const parsed = parseNumber(match[3]); flat.push({ id: `section-${match.index}`, level: match[2].length, title: parsed.text, numberParts: parsed.parts, headingFrom: match.index, headingTo: match.index + match[0].length, sectionFrom: match.index, sectionTo: text.length, parentId: null, children: [] }); }
  for (let index = 0; index < flat.length; index += 1) { const node = flat[index]; const next = flat.slice(index + 1).find(item => item.level <= node.level); node.sectionTo = next?.headingFrom ?? text.length; const parent = [...flat.slice(0, index)].reverse().find(item => item.level < node.level); if (parent) { node.parentId = parent.id; parent.children.push(node); } }
  return flat;
}
export function sectionById(text: string, id: string): SectionNode { const section = buildSectionTree(text).find(item => item.id === id); if (!section) throw new Error("找不到章节"); return section; }
function headingEdits(text: string, section: SectionNode, transform: (marks: string, title: string, node: SectionNode) => string): TextEdit[] { return buildSectionTree(text).filter(node => node.headingFrom >= section.sectionFrom && node.headingFrom < section.sectionTo).map(node => { const line = text.slice(node.headingFrom, node.headingTo); const found = /^( {0,3})(#{1,6})([ \t]+)(.*)$/.exec(line)!; return { from: node.headingFrom, to: node.headingTo, insert: transform(found[2], found[4], node) }; }); }
export function promoteSection(text: string, id: string): TextEdit[] { const section = sectionById(text, id); const targets = buildSectionTree(text).filter(node => node.headingFrom >= section.sectionFrom && node.headingFrom < section.sectionTo); if (targets.some(node => node.level === 1)) throw new Error("章节内存在一级标题，不能继续提升"); return headingEdits(text, section, (marks, title) => `${marks.slice(1)} ${title}`); }
export function demoteSection(text: string, id: string): TextEdit[] { const section = sectionById(text, id); const targets = buildSectionTree(text).filter(node => node.headingFrom >= section.sectionFrom && node.headingFrom < section.sectionTo); if (targets.some(node => node.level === 6)) throw new Error("章节内存在六级标题，不能继续降级"); return headingEdits(text, section, (marks, title) => `#${marks} ${title}`); }
export function shiftSectionNumber(text: string, id: string, delta: 1 | -1): TextEdit[] { const section = sectionById(text, id); if (!section.numberParts) throw new Error("当前标题没有可识别编号"); const changed = [...section.numberParts]; changed[changed.length - 1] += delta; if (changed.at(-1)! < 1) throw new Error("编号不得小于 1"); const oldPrefix = section.numberParts.join("."); const newPrefix = changed.join("."); const siblings = buildSectionTree(text).filter(node => node.parentId === section.parentId && node.id !== section.id); if (siblings.some(node => node.numberParts?.join(".") === newPrefix)) throw new Error("修改后与同级标题编号冲突"); return headingEdits(text, section, (_marks, title) => { const content = title.replace(new RegExp(`^${oldPrefix.replace(/\./g, "\\.")}(?=\s|\.)`), newPrefix); return `${"#".repeat(_marks.length)} ${content}`; }); }
export function deleteSection(text: string, id: string, keepHeading = false): TextEdit[] { const section = sectionById(text, id); return [{ from: section.headingFrom, to: keepHeading ? section.headingTo : section.sectionTo, insert: "" }]; }
export function moveSection(text: string, id: string, direction: "up" | "down"): TextEdit[] { const section = sectionById(text, id); const peers = buildSectionTree(text).filter(node => node.parentId === section.parentId); const index = peers.findIndex(node => node.id === id); const target = peers[index + (direction === "up" ? -1 : 1)]; if (!target) throw new Error("没有可移动的同级章节"); const sourceText = text.slice(section.sectionFrom, section.sectionTo); const targetText = text.slice(target.sectionFrom, target.sectionTo); const from = Math.min(section.sectionFrom, target.sectionFrom); const to = Math.max(section.sectionTo, target.sectionTo); return [{ from, to, insert: direction === "up" ? sourceText + targetText : targetText + sourceText }]; }
export function mergeSection(text: string, id: string, direction: "previous" | "next"): TextEdit[] { const section = sectionById(text, id); const peers = buildSectionTree(text).filter(node => node.parentId === section.parentId); const index = peers.findIndex(node => node.id === id); const target = peers[index + (direction === "previous" ? -1 : 1)]; if (!target) throw new Error("没有可合并的同级章节"); return deleteSection(text, id, true); }
export function splitSection(text: string, id: string, offset: number, title: string, level?: number): TextEdit[] { const section = sectionById(text, id); if (offset <= section.headingTo || offset >= section.sectionTo) throw new Error("拆分位置必须位于章节正文中"); return [{ from: offset, to: offset, insert: `\n\n${"#".repeat(level ?? section.level)} ${title}\n` }]; }
export function autoNumberSections(text: string): TextEdit[] { const counters = [0, 0, 0, 0, 0, 0]; return buildSectionTree(text).map(node => { counters[node.level - 1] += 1; counters.fill(0, node.level); const prefix = counters.slice(0, node.level).join("."); const old = text.slice(node.headingFrom, node.headingTo); return { from: node.headingFrom, to: node.headingTo, insert: `${"#".repeat(node.level)} ${prefix} ${node.title}` }; }); }
export function renumberSections(text: string, scopeId?: string): TextEdit[] { const all = buildSectionTree(text); const scope = scopeId ? sectionById(text, scopeId) : undefined; const selected = all.filter(node => !scope || (node.headingFrom >= scope.sectionFrom && node.headingFrom < scope.sectionTo)); const counters = [0, 0, 0, 0, 0, 0]; return selected.filter(node => node.numberParts).map(node => { counters[node.level - 1] += 1; counters.fill(0, node.level); const next = counters.slice(0, node.level).join("."); const line = text.slice(node.headingFrom, node.headingTo); return { from: node.headingFrom, to: node.headingTo, insert: line.replace(/^#+\s+\d+(?:\.\d+)*/, `${"#".repeat(node.level)} ${next}`) }; }); }
export function transform(text: string, edits: TextEdit[]): string { return applyEdits(text, edits); }
